ifeq (,$(filter usbus_cdc_ecm,$(USEMODULE)))
    USEMODULE +=  usbus_cdc_ecm
endif

ifeq (,$(filter radio,$(USEMODULE)))
    USEMODULE +=  radio
endif

ifeq (,$(filter auto_init_gnrc_netif,$(USEMODULE)))
    USEMODULE += auto_init_gnrc_netif
endif

ifeq (,$(filter border_router,$(USEMODULE)))
    USEMODULE +=  border_router
endif

ifneq(,$(filter border_router_client,$(USEMODULE)))
    USEMODULE +=  udp_client
endif
